### ISSUE TITLE
Update Kitty Giraudel's name

### ISSUE THREAD

**Issue by angeliquejw** [mkuehb/marcokuehbauch.com#1]
Hi, Marco! It looks like you have two blog posts ([see here](https://github.com/mkuehb/marcokuehbauch.com/search?q=hugo+giraudel)) that reference a previous name for Kitty Giraudel. Would you consider updating those references and links?

I considered making a PR, but somehow directly editing your blog posts felt awkward. Happy to make the PR if you prefer 👍🏻

**Comment by marcoheine-com** [comment]
Thanks so much for creating this issue and reminding me about this! Would have been perfectly fine to make a PR, I don't mind :) I just updated the posts.
